# Generated by Django 5.0 on 2024-01-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key_skills', models.TextField()),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('salary_currency', models.CharField(max_length=3)),
                ('area_name', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
