# Generated by Django 5.0 on 2024-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy',
        ),
    ]
