# Generated by Django 5.0 on 2024-01-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_vacancy_options_vacancy_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='area_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='key_skills',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
