# Generated by Django 5.0 on 2024-01-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_vacancy_area_name_alter_vacancy_key_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('BYR', models.FloatField(null=True)),
                ('USD', models.FloatField(null=True)),
                ('EUR', models.FloatField(null=True)),
                ('KZT', models.FloatField(null=True)),
                ('UAH', models.FloatField(null=True)),
                ('AZN', models.FloatField(null=True)),
                ('KGS', models.FloatField(null=True)),
                ('UZS', models.FloatField(null=True)),
                ('GEL', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'valute',
            },
        ),
    ]
