# Generated by Django 5.0 on 2024-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_city_onyear_salary_vac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_MyVac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('skill', models.TextField(null=True)),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'MyVac_skills',
                'verbose_name_plural': 'MyVac_skills',
                'db_table': 'MyVac_skills',
            },
        ),
        migrations.CreateModel(
            name='Skills_Vac_Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('skill', models.TextField(null=True)),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Skills_full',
                'verbose_name_plural': 'Skills_full',
                'db_table': 'skills_Full',
            },
        ),
    ]
